#!/usr/bin/env bash
# portwave — interactive installer
# Prompts for paths, writes ~/.config/portwave/config.env, builds release binary,
# installs it to the chosen prefix, bundles the top-ports list under
# <prefix>/../share/portwave/ports/ so the binary finds it automatically.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

C_GREEN='\033[0;32m'; C_YELLOW='\033[0;33m'; C_RED='\033[0;31m'; C_BOLD='\033[1m'; C_RESET='\033[0m'
say()  { printf "${C_GREEN}==>${C_RESET} %s\n" "$*"; }
warn() { printf "${C_YELLOW}[!]${C_RESET} %s\n" "$*"; }
die()  { printf "${C_RED}[x]${C_RESET} %s\n" "$*" >&2; exit 1; }

ask() {
  # ask "Prompt" "default"  -> echoes answer
  local prompt="$1"; local default="${2:-}"; local reply
  if [[ -n "$default" ]]; then
    read -r -p "$(printf "${C_BOLD}?${C_RESET} %s [%s]: " "$prompt" "$default")" reply
    echo "${reply:-$default}"
  else
    read -r -p "$(printf "${C_BOLD}?${C_RESET} %s: " "$prompt")" reply
    echo "$reply"
  fi
}

detect() { command -v "$1" 2>/dev/null || true; }

printf "\n${C_BOLD}portwave installer${C_RESET}\n\n"

# ── 1. Rust toolchain ──
if ! command -v cargo >/dev/null 2>&1; then
  warn "cargo not found."
  if [[ "$(ask "Install Rust via rustup now?" "yes")" =~ ^[Yy] ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    # shellcheck source=/dev/null
    source "$HOME/.cargo/env"
  else
    die "cargo is required. Install Rust and retry."
  fi
fi
say "cargo: $(cargo --version)"

# ── 2. Prompts ──
DEFAULT_OUTPUT="${HOME}/scans"
DEFAULT_PREFIX="${HOME}/.local/bin"
if [[ -w "/usr/local/bin" ]]; then DEFAULT_PREFIX="/usr/local/bin"; fi

BUNDLED_PORTS="$REPO_ROOT/ports/portwave-top-ports.txt"

printf "\nConfigure paths (press Enter to accept defaults):\n"
OUTPUT_DIR="$(ask "Scan output directory" "$DEFAULT_OUTPUT")"
PORTS_FILE="$(ask "Ports file (leave default to use bundled 427-port list)" "$BUNDLED_PORTS")"
HTTPX_BIN="$(ask  "Path to httpx  binary (optional)" "$(detect httpx)")"
NUCLEI_BIN="$(ask "Path to nuclei binary (optional)" "$(detect nuclei)")"
INSTALL_PREFIX="$(ask "Install binary to" "$DEFAULT_PREFIX")"

SHARE_DIR="$(dirname "$INSTALL_PREFIX")/share/portwave"
CONFIG_DIR="${HOME}/.config/portwave"
CONFIG_FILE="${CONFIG_DIR}/config.env"

mkdir -p "$OUTPUT_DIR" "$CONFIG_DIR" "$SHARE_DIR/ports" "$INSTALL_PREFIX"

# ── 3. Build ──
say "Building release binary (this takes ~30–60 s on first run)…"
cargo build --release

BIN_SRC="$REPO_ROOT/target/release/portwave"
[[ -x "$BIN_SRC" ]] || die "Build succeeded but binary not found at $BIN_SRC"

# ── 4. Install artefacts ──
install -m 0755 "$BIN_SRC" "$INSTALL_PREFIX/portwave"
install -m 0644 "$BUNDLED_PORTS" "$SHARE_DIR/ports/portwave-top-ports.txt"

# ── 5. Write config ──
{
  echo "# Generated by portwave install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "PORTWAVE_OUTPUT_DIR=$OUTPUT_DIR"
  echo "PORTWAVE_PORTS=$PORTS_FILE"
  [[ -n "$HTTPX_BIN"  ]] && echo "PORTWAVE_HTTPX_BIN=$HTTPX_BIN"
  [[ -n "$NUCLEI_BIN" ]] && echo "PORTWAVE_NUCLEI_BIN=$NUCLEI_BIN"
} > "$CONFIG_FILE"
chmod 0600 "$CONFIG_FILE"
say "Wrote config: $CONFIG_FILE"

# ── 6. PATH hint ──
case ":$PATH:" in
  *":$INSTALL_PREFIX:"*) ;;
  *) warn "$INSTALL_PREFIX is not on your \$PATH. Add:  export PATH=\"$INSTALL_PREFIX:\$PATH\"  to your shell rc." ;;
esac

# ── 7. Sanity ──
if "$INSTALL_PREFIX/portwave" --version >/dev/null 2>&1; then
  say "Installed: $("$INSTALL_PREFIX/portwave" --version)"
else
  die "Install test failed."
fi

printf "\n${C_GREEN}Done.${C_RESET} Try:  portwave demo 127.0.0.1/32 --no-httpx --no-nuclei\n\n"
